pub enum PrecompiledInstruction {
    Cache,
    BeforeAsyncWith,
    BeforeWith,
    BinaryOpInplaceAddUnicode,
    BinarySlice,
    BinarySubscr,
    CheckEgMatch,
    CheckExcMatch,
    CleanupThrow,
    DeleteSubscr,
    EndAsyncFor,
    EndFor,
    EndSend,
    ExitInitCheck,
    FormatSimple,
    FormatWithSpec,
    GetAiter,
    Reserved,
    GetAnext,
    GetIter,
    GetLen,
    GetYieldFromIter,
    InterpreterExit,
    LoadAssertionError,
    LoadBuildClass,
    LoadLocals,
    MakeFunction,
    MatchKeys,
    MatchMapping,
    MatchSequence,
    Nop,
    PopExcept,
    PopTop,
    PushExcInfo,
    PushNull,
    ReturnGenerator,
    ReturnValue,
    SetupAnnotations,
    StoreSlice,
    StoreSubscr,
    ToBool,
    UnaryInvert,
    UnaryNegative,
    UnaryNot,
    WithExceptStart,
    BinaryOp,
    BuildConstKeyMap,
    BuildList,
    BuildMap,
    BuildSet,
    BuildSlice,
    BuildString,
    BuildTuple,
    Call,
    CallFunctionEx,
    CallIntrinsic1,
    CallIntrinsic2,
    CallKw,
    CompareOp,
    ContainsOp,
    ConvertValue,
    Copy,
    CopyFreeVars,
    DeleteAttr,
    DeleteDeref,
    DeleteFast,
    DeleteGlobal,
    DeleteName,
    DictMerge,
    DictUpdate,
    EnterExecutor,
    ExtendedArg,
    ForIter,
    GetAwaitable,
    ImportFrom,
    ImportName,
    IsOp,
    JumpBackward,
    JumpBackwardNoInterrupt,
    JumpForward,
    ListAppend,
    ListExtend,
    LoadAttr,
    LoadConst,
    LoadDeref,
    LoadFast,
    LoadFastAndClear,
    LoadFastCheck,
    LoadFastLoadFast,
    LoadFromDictOrDeref,
    LoadFromDictOrGlobals,
    LoadGlobal,
    LoadName,
    LoadSuperAttr,
    MakeCell,
    MapAdd,
    MatchClass,
    PopJumpIfFalse,
    PopJumpIfNone,
    PopJumpIfNotNone,
    PopJumpIfTrue,
    RaiseVarargs,
    Reraise,
    ReturnConst,
    Send,
    SetAdd,
    SetFunctionAttribute,
    SetUpdate,
    StoreAttr,
    StoreDeref,
    StoreFast,
    StoreFastLoadFast,
    StoreFastStoreFast,
    StoreGlobal,
    StoreName,
    Swap,
    UnpackEx,
    UnpackSequence,
    YieldValue,
    Resume,
    BinaryOpAddFloat,
    BinaryOpAddInt,
    BinaryOpAddUnicode,
    BinaryOpMultiplyFloat,
    BinaryOpMultiplyInt,
    BinaryOpSubtractFloat,
    BinaryOpSubtractInt,
    BinarySubscrDict,
    BinarySubscrGetitem,
    BinarySubscrListInt,
    BinarySubscrStrInt,
    BinarySubscrTupleInt,
    CallAllocAndEnterInit,
    CallBoundMethodExactArgs,
    CallBuiltinClass,
    CallBuiltinFast,
    CallBuiltinFastWithKeywords,
    CallBuiltinO,
    CallIsinstance,
    CallLen,
    CallListAppend,
    CallMethodDescriptorFast,
    CallMethodDescriptorFastWithKeywords,
    CallMethodDescriptorNoargs,
    CallMethodDescriptorO,
    CallPyExactArgs,
    CallPyWithDefaults,
    CallStr1,
    CallTuple1,
    CallType1,
    CompareOpFloat,
    CompareOpInt,
    CompareOpStr,
    ForIterGen,
    ForIterList,
    ForIterRange,
    ForIterTuple,
    LoadAttrClass,
    LoadAttrGetattributeOverridden,
    LoadAttrInstanceValue,
    LoadAttrMethodLazyDict,
    LoadAttrMethodNoDict,
    LoadAttrMethodWithValues,
    LoadAttrModule,
    LoadAttrNondescriptorNoDict,
    LoadAttrNondescriptorWithValues,
    LoadAttrProperty,
    LoadAttrSlot,
    LoadAttrWithHint,
    LoadGlobalBuiltin,
    LoadGlobalModule,
    LoadSuperAttrAttr,
    LoadSuperAttrMethod,
    ResumeCheck,
    SendGen,
    StoreAttrInstanceValue,
    StoreAttrSlot,
    StoreAttrWithHint,
    StoreSubscrDict,
    StoreSubscrListInt,
    ToBoolAlwaysTrue,
    ToBoolBool,
    ToBoolInt,
    ToBoolList,
    ToBoolNone,
    ToBoolStr,
    UnpackSequenceList,
    UnpackSequenceTuple,
    UnpackSequenceTwoTuple,
    InstrumentedResume,
    InstrumentedEndFor,
    InstrumentedEndSend,
    InstrumentedReturnValue,
    InstrumentedReturnConst,
    InstrumentedYieldValue,
    InstrumentedLoadSuperAttr,
    InstrumentedForIter,
    InstrumentedCall,
    InstrumentedCallKw,
    InstrumentedCallFunctionEx,
    InstrumentedInstruction,
    InstrumentedJumpForward,
    InstrumentedJumpBackward,
    InstrumentedPopJumpIfTrue,
    InstrumentedPopJumpIfFalse,
    InstrumentedPopJumpIfNone,
    InstrumentedPopJumpIfNotNone,
    InstrumentedLine,
    Jump,
    JumpNoInterrupt,
    LoadClosure,
    LoadMethod,
    LoadSuperMethod,
    LoadZeroSuperAttr,
    LoadZeroSuperMethod,
    PopBlock,
    SetupCleanup,
    SetupFinally,
    SetupWith,
    StoreFastMaybeNull,
    //
    HaveArgument, // 44
    MinInstrumentedOpcode, // 236
}

impl PrecompiledInstruction {
    pub fn from_byte(byte: &u16) -> Option<Self> {
        match byte {
            0 => Some(PrecompiledInstruction::Cache),
            1 => Some(PrecompiledInstruction::BeforeAsyncWith),
            2 => Some(PrecompiledInstruction::BeforeWith),
            3 => Some(PrecompiledInstruction::BinaryOpInplaceAddUnicode),
            4 => Some(PrecompiledInstruction::BinarySlice),
            5 => Some(PrecompiledInstruction::BinarySubscr),
            6 => Some(PrecompiledInstruction::CheckEgMatch),
            7 => Some(PrecompiledInstruction::CheckExcMatch),
            8 => Some(PrecompiledInstruction::CleanupThrow),
            9 => Some(PrecompiledInstruction::DeleteSubscr),
            10 => Some(PrecompiledInstruction::EndAsyncFor),
            11 => Some(PrecompiledInstruction::EndFor),
            12 => Some(PrecompiledInstruction::EndSend),
            13 => Some(PrecompiledInstruction::ExitInitCheck),
            14 => Some(PrecompiledInstruction::FormatSimple),
            15 => Some(PrecompiledInstruction::FormatWithSpec),
            16 => Some(PrecompiledInstruction::GetAiter),
            17 => Some(PrecompiledInstruction::Reserved),
            18 => Some(PrecompiledInstruction::GetAnext),
            19 => Some(PrecompiledInstruction::GetIter),
            20 => Some(PrecompiledInstruction::GetLen),
            21 => Some(PrecompiledInstruction::GetYieldFromIter),
            22 => Some(PrecompiledInstruction::InterpreterExit),
            23 => Some(PrecompiledInstruction::LoadAssertionError),
            24 => Some(PrecompiledInstruction::LoadBuildClass),
            25 => Some(PrecompiledInstruction::LoadLocals),
            26 => Some(PrecompiledInstruction::MakeFunction),
            27 => Some(PrecompiledInstruction::MatchKeys),
            28 => Some(PrecompiledInstruction::MatchMapping),
            29 => Some(PrecompiledInstruction::MatchSequence),
            30 => Some(PrecompiledInstruction::Nop),
            31 => Some(PrecompiledInstruction::PopExcept),
            32 => Some(PrecompiledInstruction::PopTop),
            33 => Some(PrecompiledInstruction::PushExcInfo),
            34 => Some(PrecompiledInstruction::PushNull),
            35 => Some(PrecompiledInstruction::ReturnGenerator),
            36 => Some(PrecompiledInstruction::ReturnValue),
            37 => Some(PrecompiledInstruction::SetupAnnotations),
            38 => Some(PrecompiledInstruction::StoreSlice),
            39 => Some(PrecompiledInstruction::StoreSubscr),
            40 => Some(PrecompiledInstruction::ToBool),
            41 => Some(PrecompiledInstruction::UnaryInvert),
            42 => Some(PrecompiledInstruction::UnaryNegative),
            43 => Some(PrecompiledInstruction::UnaryNot),
            44 => Some(PrecompiledInstruction::WithExceptStart),
            45 => Some(PrecompiledInstruction::BinaryOp),
            46 => Some(PrecompiledInstruction::BuildConstKeyMap),
            47 => Some(PrecompiledInstruction::BuildList),
            48 => Some(PrecompiledInstruction::BuildMap),
            49 => Some(PrecompiledInstruction::BuildSet),
            50 => Some(PrecompiledInstruction::BuildSlice),
            51 => Some(PrecompiledInstruction::BuildString),
            52 => Some(PrecompiledInstruction::BuildTuple),
            53 => Some(PrecompiledInstruction::Call),
            54 => Some(PrecompiledInstruction::CallFunctionEx),
            55 => Some(PrecompiledInstruction::CallIntrinsic1),
            56 => Some(PrecompiledInstruction::CallIntrinsic2),
            57 => Some(PrecompiledInstruction::CallKw),
            58 => Some(PrecompiledInstruction::CompareOp),
            59 => Some(PrecompiledInstruction::ContainsOp),
            60 => Some(PrecompiledInstruction::ConvertValue),
            61 => Some(PrecompiledInstruction::Copy),
            62 => Some(PrecompiledInstruction::CopyFreeVars),
            63 => Some(PrecompiledInstruction::DeleteAttr),
            64 => Some(PrecompiledInstruction::DeleteDeref),
            65 => Some(PrecompiledInstruction::DeleteFast),
            66 => Some(PrecompiledInstruction::DeleteGlobal),
            67 => Some(PrecompiledInstruction::DeleteName),
            68 => Some(PrecompiledInstruction::DictMerge),
            69 => Some(PrecompiledInstruction::DictUpdate),
            70 => Some(PrecompiledInstruction::EnterExecutor),
            71 => Some(PrecompiledInstruction::ExtendedArg),
            72 => Some(PrecompiledInstruction::ForIter),
            73 => Some(PrecompiledInstruction::GetAwaitable),
            74 => Some(PrecompiledInstruction::ImportFrom),
            75 => Some(PrecompiledInstruction::ImportName),
            76 => Some(PrecompiledInstruction::IsOp),
            77 => Some(PrecompiledInstruction::JumpBackward),
            78 => Some(PrecompiledInstruction::JumpBackwardNoInterrupt),
            79 => Some(PrecompiledInstruction::JumpForward),
            80 => Some(PrecompiledInstruction::ListAppend),
            81 => Some(PrecompiledInstruction::ListExtend),
            82 => Some(PrecompiledInstruction::LoadAttr),
            83 => Some(PrecompiledInstruction::LoadConst),
            84 => Some(PrecompiledInstruction::LoadDeref),
            85 => Some(PrecompiledInstruction::LoadFast),
            86 => Some(PrecompiledInstruction::LoadFastAndClear),
            87 => Some(PrecompiledInstruction::LoadFastCheck),
            88 => Some(PrecompiledInstruction::LoadFastLoadFast),
            89 => Some(PrecompiledInstruction::LoadFromDictOrDeref),
            90 => Some(PrecompiledInstruction::LoadFromDictOrGlobals),
            91 => Some(PrecompiledInstruction::LoadGlobal),
            92 => Some(PrecompiledInstruction::LoadName),
            93 => Some(PrecompiledInstruction::LoadSuperAttr),
            94 => Some(PrecompiledInstruction::MakeCell),
            95 => Some(PrecompiledInstruction::MapAdd),
            96 => Some(PrecompiledInstruction::MatchClass),
            97 => Some(PrecompiledInstruction::PopJumpIfFalse),
            98 => Some(PrecompiledInstruction::PopJumpIfNone),
            99 => Some(PrecompiledInstruction::PopJumpIfNotNone),
            100 => Some(PrecompiledInstruction::PopJumpIfTrue),
            101 => Some(PrecompiledInstruction::RaiseVarargs),
            102 => Some(PrecompiledInstruction::Reraise),
            103 => Some(PrecompiledInstruction::ReturnConst),
            104 => Some(PrecompiledInstruction::Send),
            105 => Some(PrecompiledInstruction::SetAdd),
            106 => Some(PrecompiledInstruction::SetFunctionAttribute),
            107 => Some(PrecompiledInstruction::SetUpdate),
            108 => Some(PrecompiledInstruction::StoreAttr),
            109 => Some(PrecompiledInstruction::StoreDeref),
            110 => Some(PrecompiledInstruction::StoreFast),
            111 => Some(PrecompiledInstruction::StoreFastLoadFast),
            112 => Some(PrecompiledInstruction::StoreFastStoreFast),
            113 => Some(PrecompiledInstruction::StoreGlobal),
            114 => Some(PrecompiledInstruction::StoreName),
            115 => Some(PrecompiledInstruction::Swap),
            116 => Some(PrecompiledInstruction::UnpackEx),
            117 => Some(PrecompiledInstruction::UnpackSequence),
            118 => Some(PrecompiledInstruction::YieldValue),
            149 => Some(PrecompiledInstruction::Resume),
            150 => Some(PrecompiledInstruction::BinaryOpAddFloat),
            151 => Some(PrecompiledInstruction::BinaryOpAddInt),
            152 => Some(PrecompiledInstruction::BinaryOpAddUnicode),
            153 => Some(PrecompiledInstruction::BinaryOpMultiplyFloat),
            154 => Some(PrecompiledInstruction::BinaryOpMultiplyInt),
            155 => Some(PrecompiledInstruction::BinaryOpSubtractFloat),
            156 => Some(PrecompiledInstruction::BinaryOpSubtractInt),
            157 => Some(PrecompiledInstruction::BinarySubscrDict),
            158 => Some(PrecompiledInstruction::BinarySubscrGetitem),
            159 => Some(PrecompiledInstruction::BinarySubscrListInt),
            160 => Some(PrecompiledInstruction::BinarySubscrStrInt),
            161 => Some(PrecompiledInstruction::BinarySubscrTupleInt),
            162 => Some(PrecompiledInstruction::CallAllocAndEnterInit),
            163 => Some(PrecompiledInstruction::CallBoundMethodExactArgs),
            164 => Some(PrecompiledInstruction::CallBuiltinClass),
            165 => Some(PrecompiledInstruction::CallBuiltinFast),
            166 => Some(PrecompiledInstruction::CallBuiltinFastWithKeywords),
            167 => Some(PrecompiledInstruction::CallBuiltinO),
            168 => Some(PrecompiledInstruction::CallIsinstance),
            169 => Some(PrecompiledInstruction::CallLen),
            170 => Some(PrecompiledInstruction::CallListAppend),
            171 => Some(PrecompiledInstruction::CallMethodDescriptorFast),
            172 => Some(PrecompiledInstruction::CallMethodDescriptorFastWithKeywords),
            173 => Some(PrecompiledInstruction::CallMethodDescriptorNoargs),
            174 => Some(PrecompiledInstruction::CallMethodDescriptorO),
            175 => Some(PrecompiledInstruction::CallPyExactArgs),
            176 => Some(PrecompiledInstruction::CallPyWithDefaults),
            177 => Some(PrecompiledInstruction::CallStr1),
            178 => Some(PrecompiledInstruction::CallTuple1),
            179 => Some(PrecompiledInstruction::CallType1),
            180 => Some(PrecompiledInstruction::CompareOpFloat),
            181 => Some(PrecompiledInstruction::CompareOpInt),
            182 => Some(PrecompiledInstruction::CompareOpStr),
            183 => Some(PrecompiledInstruction::ForIterGen),
            184 => Some(PrecompiledInstruction::ForIterList),
            185 => Some(PrecompiledInstruction::ForIterRange),
            186 => Some(PrecompiledInstruction::ForIterTuple),
            187 => Some(PrecompiledInstruction::LoadAttrClass),
            188 => Some(PrecompiledInstruction::LoadAttrGetattributeOverridden),
            189 => Some(PrecompiledInstruction::LoadAttrInstanceValue),
            190 => Some(PrecompiledInstruction::LoadAttrMethodLazyDict),
            191 => Some(PrecompiledInstruction::LoadAttrMethodNoDict),
            192 => Some(PrecompiledInstruction::LoadAttrMethodWithValues),
            193 => Some(PrecompiledInstruction::LoadAttrModule),
            194 => Some(PrecompiledInstruction::LoadAttrNondescriptorNoDict),
            195 => Some(PrecompiledInstruction::LoadAttrNondescriptorWithValues),
            196 => Some(PrecompiledInstruction::LoadAttrProperty),
            197 => Some(PrecompiledInstruction::LoadAttrSlot),
            198 => Some(PrecompiledInstruction::LoadAttrWithHint),
            199 => Some(PrecompiledInstruction::LoadGlobalBuiltin),
            200 => Some(PrecompiledInstruction::LoadGlobalModule),
            201 => Some(PrecompiledInstruction::LoadSuperAttrAttr),
            202 => Some(PrecompiledInstruction::LoadSuperAttrMethod),
            203 => Some(PrecompiledInstruction::ResumeCheck),
            204 => Some(PrecompiledInstruction::SendGen),
            205 => Some(PrecompiledInstruction::StoreAttrInstanceValue),
            206 => Some(PrecompiledInstruction::StoreAttrSlot),
            207 => Some(PrecompiledInstruction::StoreAttrWithHint),
            208 => Some(PrecompiledInstruction::StoreSubscrDict),
            209 => Some(PrecompiledInstruction::StoreSubscrListInt),
            210 => Some(PrecompiledInstruction::ToBoolAlwaysTrue),
            211 => Some(PrecompiledInstruction::ToBoolBool),
            212 => Some(PrecompiledInstruction::ToBoolInt),
            213 => Some(PrecompiledInstruction::ToBoolList),
            214 => Some(PrecompiledInstruction::ToBoolNone),
            215 => Some(PrecompiledInstruction::ToBoolStr),
            216 => Some(PrecompiledInstruction::UnpackSequenceList),
            217 => Some(PrecompiledInstruction::UnpackSequenceTuple),
            218 => Some(PrecompiledInstruction::UnpackSequenceTwoTuple),
            236 => Some(PrecompiledInstruction::InstrumentedResume),
            237 => Some(PrecompiledInstruction::InstrumentedEndFor),
            238 => Some(PrecompiledInstruction::InstrumentedEndSend),
            239 => Some(PrecompiledInstruction::InstrumentedReturnValue),
            240 => Some(PrecompiledInstruction::InstrumentedReturnConst),
            241 => Some(PrecompiledInstruction::InstrumentedYieldValue),
            242 => Some(PrecompiledInstruction::InstrumentedLoadSuperAttr),
            243 => Some(PrecompiledInstruction::InstrumentedForIter),
            244 => Some(PrecompiledInstruction::InstrumentedCall),
            245 => Some(PrecompiledInstruction::InstrumentedCallKw),
            246 => Some(PrecompiledInstruction::InstrumentedCallFunctionEx),
            247 => Some(PrecompiledInstruction::InstrumentedInstruction),
            248 => Some(PrecompiledInstruction::InstrumentedJumpForward),
            249 => Some(PrecompiledInstruction::InstrumentedJumpBackward),
            250 => Some(PrecompiledInstruction::InstrumentedPopJumpIfTrue),
            251 => Some(PrecompiledInstruction::InstrumentedPopJumpIfFalse),
            252 => Some(PrecompiledInstruction::InstrumentedPopJumpIfNone),
            253 => Some(PrecompiledInstruction::InstrumentedPopJumpIfNotNone),
            254 => Some(PrecompiledInstruction::InstrumentedLine),
            256 => Some(PrecompiledInstruction::Jump),
            257 => Some(PrecompiledInstruction::JumpNoInterrupt),
            258 => Some(PrecompiledInstruction::LoadClosure),
            259 => Some(PrecompiledInstruction::LoadMethod),
            260 => Some(PrecompiledInstruction::LoadSuperMethod),
            261 => Some(PrecompiledInstruction::LoadZeroSuperAttr),
            262 => Some(PrecompiledInstruction::LoadZeroSuperMethod),
            263 => Some(PrecompiledInstruction::PopBlock),
            264 => Some(PrecompiledInstruction::SetupCleanup),
            265 => Some(PrecompiledInstruction::SetupFinally),
            266 => Some(PrecompiledInstruction::SetupWith),
            267 => Some(PrecompiledInstruction::StoreFastMaybeNull),

            // 44 => Some(Instruction::HaveArgument),
            // 236 => Some(Instruction::MinInstrumentedOpcode),

            _ => None
        }
    }
}